puts "THe Students of Villains Academy"
puts "-------------------"
puts "Henry Lecter"
puts "Luke Vader"
puts "The Troubled Wicken of the Southwest"
puts "Disruptinator"
puts "Frederic Kreuger"
puts "The Chuckler"
puts "Norma Bates"
puts "BoJo"
